global using CustomerSupportSystem.Core.Contracts;
global using CustomerSupportSystem.Core.Models;
global using CustomerSupportSystem.Core.Models.Contact;
global using CustomerSupportSystem.Infrastructure.Constants;
global using CustomerSupportSystem.Infrastructure.Data.Common;
global using CustomerSupportSystem.Infrastructure.Data.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel.DataAnnotations;
